name: Merge Unit Tests

on:
  push:
    branches: [ MOB-2012_firefox_120_upgrade ]


jobs:
  execute_merge_tests:
    runs-on: macos-13
    name: Execute Merge Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: ./.github/actions/prepare_environment
        with:
          core-token: ${{ secrets.IOS_CORE_TOKEN }}

      - name: Run tests based on file changes
        shell: bash
        run: |
          bundle exec fastlane run run_tests build_for_testing:true
          bundle exec fastlane run run_tests test_without_building:true testplan:"UnitTest"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.7.6
        with:
          report_paths: '**/test_output/xml/report.junit'
          github_token: ${{ inputs.github-token }}

      # - name: Evaluate Tests to execute
      #   id: evaluate-tests-to-execute
      #   uses: ./.github/actions/evaluate_tests_to_execute

      # - name: Perform Tests and Publish Test reports
      #   id: perform-tests
      #   uses: ./.github/actions/perform_tests
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}  